instrumentation:
  include-all-sources: true
reporting:
  reports:
    - html
check:
  global:
    statements: 100
    lines: 100
    branches: 100
    functions: 100
  each:
    statements: 100
    lines: 100
    branches: 100
    functions: 100
